# Build clap-saw-demo

trigger:
  - main

pr:
  - main

jobs:

  - job: Build
    strategy:
      matrix:
        mac:
          imageName: 'macos-latest'
          isMac: True
        win:
          imageName: 'windows-2019'
          isWindows: True
        lin:
          imageName: 'ubuntu-latest'
          isLinux: True

    pool:
      vmImage: $(imageName)

    steps:
      - checkout: self
        fetchDepth: 1

      - bash: |
          set -e
          
          
          sudo apt-get update

          sudo apt-get install -y \
            devscripts \
            libxcb-cursor-dev \
            libxcb-keysyms1-dev \
            libxcb-util-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            ninja-build \
            libcogl-pango-dev \
            libpangoft2-1.0-0 \
            libpango-1.0-0 \
            libgtk-3-dev \
            libgtkmm-3.0-dev \
            xcb
        displayName: apt-get
        condition: variables.isLinux

      - bash: |
          git submodule update --init --recursive
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
        displayName: Submodules and First Cmake

      - bash: |
          cmake --build build --target clap-saw-demo
        displayName: Build clap-saw-demo
